#SpringBoot所有的配置类，都有一个自动配置类#
#自动配置类都会绑定一个 properties 配置文件  RedisProperties

spring:
  redis:
    host: 192.168.63.4
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 159753
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
mybatis:
  type-aliases-package: com.du.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  servlet:
    context-path: /du
  port: 8080


